

### Create Product
POST http://localhost:5400/product/createProduct
Content-Type: application/json

{
    "productName": "Harry Porter",
    "productDescription": "Explore breathtaking landscapes and exciting activities.",
    "productPrice": 5000,
    "productCategory": "Electronics",
    "productImage": "https://m.media-amazon.com/images/I/61k7JqSWOUL._SY425_.jpg",
    "supplierContact": "Penguin",
    "Quantity": 20
}

### Get All Products
GET http://localhost:5400/product/


### update product

PUT  http://localhost:5400/product/updateProduct
Content-Type: application/json

{   
    "productID":"5cc3bcd0-63ae-4bea-b82f-b865b0ff8436",
    "productName": "Hunger Games",
    "productDescription": "adventures",
    "productPrice": 6000,
    "productCategory": "Electronics",
    "productImage": "https://m.media-amazon.com/images/I/61k7JqSWOUL._SY425_.jpg",
    "supplierContact": "Penguins",
    "Quantity": 19
}

###delete product
DELETE  http://localhost:5400/product/deleteproduct
Content-Type: application/json

{  

    "productID":"5cc3bcd0-63ae-4bea-b82f-b865b0ff8436"
  
}
